package com.sop.miniprogrambackend.model.data;

public class ClockInDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_clock_in.id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_clock_in.user_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_clock_in.course_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_clock_in.done
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    private Byte done;

    private String recordPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_clock_in.id
     *
     * @return the value of mp_clock_in.id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_clock_in.id
     *
     * @param id the value for mp_clock_in.id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_clock_in.user_id
     *
     * @return the value of mp_clock_in.user_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_clock_in.user_id
     *
     * @param userId the value for mp_clock_in.user_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_clock_in.course_id
     *
     * @return the value of mp_clock_in.course_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_clock_in.course_id
     *
     * @param courseId the value for mp_clock_in.course_id
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_clock_in.done
     *
     * @return the value of mp_clock_in.done
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public Byte getDone() {
        return done;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_clock_in.done
     *
     * @param done the value for mp_clock_in.done
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    public void setDone(Byte done) {
        this.done = done;
    }

    public String getRecordPath() {
        return recordPath;
    }

    public void setRecordPath(String recordPath) {
        this.recordPath = recordPath;
    }
}