package com.sop.miniprogrambackend.model.data;

public class CollectThumbsUpDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.user_id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.work_name
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private String workName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.img_path
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.thumbs_up_count
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private Integer thumbsUpCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_collect_thumbs_up.work_profile
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    private String workProfile;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.id
     *
     * @return the value of mp_collect_thumbs_up.id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.id
     *
     * @param id the value for mp_collect_thumbs_up.id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.user_id
     *
     * @return the value of mp_collect_thumbs_up.user_id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.user_id
     *
     * @param userId the value for mp_collect_thumbs_up.user_id
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.work_name
     *
     * @return the value of mp_collect_thumbs_up.work_name
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public String getWorkName() {
        return workName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.work_name
     *
     * @param workName the value for mp_collect_thumbs_up.work_name
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setWorkName(String workName) {
        this.workName = workName == null ? null : workName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.img_path
     *
     * @return the value of mp_collect_thumbs_up.img_path
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.img_path
     *
     * @param imgPath the value for mp_collect_thumbs_up.img_path
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.thumbs_up_count
     *
     * @return the value of mp_collect_thumbs_up.thumbs_up_count
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public Integer getThumbsUpCount() {
        return thumbsUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.thumbs_up_count
     *
     * @param thumbsUpCount the value for mp_collect_thumbs_up.thumbs_up_count
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setThumbsUpCount(Integer thumbsUpCount) {
        this.thumbsUpCount = thumbsUpCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_collect_thumbs_up.work_profile
     *
     * @return the value of mp_collect_thumbs_up.work_profile
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public String getWorkProfile() {
        return workProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_collect_thumbs_up.work_profile
     *
     * @param workProfile the value for mp_collect_thumbs_up.work_profile
     *
     * @mbg.generated Wed Jun 26 22:06:08 CST 2019
     */
    public void setWorkProfile(String workProfile) {
        this.workProfile = workProfile == null ? null : workProfile.trim();
    }
}