package com.sop.miniprogrambackend.model.data;

public class UserWxDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_wx.openid
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_wx.session_key
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    private String sessionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_wx.code
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mp_user_wx.user_id
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_wx.openid
     *
     * @return the value of mp_user_wx.openid
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_wx.openid
     *
     * @param openid the value for mp_user_wx.openid
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_wx.session_key
     *
     * @return the value of mp_user_wx.session_key
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_wx.session_key
     *
     * @param sessionKey the value for mp_user_wx.session_key
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_wx.code
     *
     * @return the value of mp_user_wx.code
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_wx.code
     *
     * @param code the value for mp_user_wx.code
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mp_user_wx.user_id
     *
     * @return the value of mp_user_wx.user_id
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mp_user_wx.user_id
     *
     * @param userId the value for mp_user_wx.user_id
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}