package com.sop.miniprogrambackend.model;

import com.sop.miniprogrambackend.model.data.AdminDO;

public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    AdminDO selectByPrimaryKey(Integer id);

    AdminDO selectByUsernamePassword(String username, String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_admin
     *
     * @mbg.generated Thu Jul 18 00:18:55 CST 2019
     */
    int updateByPrimaryKey(AdminDO record);
}