package com.sop.miniprogrambackend.model;

import com.sop.miniprogrambackend.model.data.CourseDO;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    CourseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_course
     *
     * @mbg.generated Tue Jun 25 14:00:02 CST 2019
     */
    int updateByPrimaryKey(CourseDO record);
}