package com.sop.miniprogrambackend.model;

import com.sop.miniprogrambackend.model.data.UserWxDO;

public interface UserWxDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    int insert(UserWxDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    int insertSelective(UserWxDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    UserWxDO selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    int updateByPrimaryKeySelective(UserWxDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mp_user_wx
     *
     * @mbg.generated Sun Jun 23 20:28:27 CST 2019
     */
    int updateByPrimaryKey(UserWxDO record);
}